/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamo;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class VentanaPrestamo extends javax.swing.JFrame {

    private DefaultTableModel tabla;
    private ArrayList<ArrayPrestamos> prestamos;
    public VentanaPrestamo() {
        initComponents();
        
        //Inicialización de atributos.
        tabla = (DefaultTableModel) jTable1.getModel();
        prestamos = new ArrayList<>();
                
        //Propiedades de interfaz
        jTable1.setAutoResizeMode(0);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        capitalInicial = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tasaInteres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diasPrestamo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalIngresos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Capital Inicial:");

        jLabel2.setText("Interés (%):");

        jLabel3.setText("Días Préstamo:");

        jButton1.setText("Genenrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(jTable1);

        totalIngresos.setText("Total Ingresos: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(capitalInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tasaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(totalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(capitalInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tasaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(diasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalIngresos)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Generación de columnas.
        Integer dPrestamo = Integer.parseInt(this.diasPrestamo.getText());
        for (int i = 0; i <= dPrestamo * 2; i++) {
            if (i == 0) {
                tabla.addColumn("Capital Inicial");
            }
            else {
                tabla.addColumn("Día" + (i));
            }
        }
        
        //Abstracción de variables.
        Double capitalInicial = Double.parseDouble(this.capitalInicial.getText());
        Double interes = Double.parseDouble(this.tasaInteres.getText()) / 100;
        Double cuotaSecundaria = ((interes * capitalInicial) + capitalInicial) / dPrestamo;
        
        
        //Creación de filas.
        ArrayPrestamos prestamo;
        for (int i = 1; i <= dPrestamo + 1; i++) {
            if (i == 1) {
                prestamo = new ArrayPrestamos(interes, capitalInicial, dPrestamo, i);
                prestamo.generarPrestamosAutomaticos();
                prestamo.mostrarCuotas();
                prestamos.add(prestamo);
            }
            else {
                prestamo = new ArrayPrestamos(interes, cuotaSecundaria, dPrestamo, i);
                prestamo.generarPrestamosAutomaticos();
                prestamo.mostrarCuotas();
                prestamos.add(prestamo);
            }
        }
        addToTable();
        totalIngresos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField capitalInicial;
    private javax.swing.JTextField diasPrestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tasaInteres;
    private javax.swing.JLabel totalIngresos;
    // End of variables declaration//GEN-END:variables

    private void addToTable() {
        ArrayList<NuevoPrestamo> prestamoActual;
        int counter = 0;
        for (ArrayPrestamos prestamo : prestamos) {
            
            //Creamos una nueva fila para poner los datos.
            tabla.setRowCount(counter + 1);
            jTable1.setValueAt(prestamo.getCapitalInicial(), counter, 0);
            prestamoActual = prestamo.getCarritoPrestamo();
            for (NuevoPrestamo nuevoPrestamo : prestamoActual) {
                jTable1.setValueAt(nuevoPrestamo.getValorPrestamo(), counter, nuevoPrestamo.getDiaPrestamo());
            }
            
            counter++;
        }
        
        Double totalDiario;
        int filasFinales = 1;
        tabla.setRowCount(counter + 1);
        jTable1.setValueAt("TOTAL DÍA", counter, 0);
        
        for (int i = 1; i <= tabla.getColumnCount() / 2; i++) {
            totalDiario = 0.0;
            for (int j = 0; j < i; j++) {
                totalDiario += (Double) jTable1.getValueAt(j, i);
            }
            jTable1.setValueAt(totalDiario, counter, i);
        }
        
        
        for (int i = (tabla.getColumnCount() / 2) + 1; i < tabla.getColumnCount(); i++) {
            totalDiario = 0.0;
            
            for (int j = filasFinales; j < counter; j++) {
                totalDiario += (Double) jTable1.getValueAt(j, i);
            }
            filasFinales++;
            jTable1.setValueAt(totalDiario, counter, i);
        }
        
    }
    
    private void totalIngresos() {
        Double total = 0.0;
        for (int i = 1; i < tabla.getColumnCount(); i++) {
            total += (Double) jTable1.getValueAt(tabla.getRowCount() - 1, i);
        }
        this.totalIngresos.setText("Total Ingresos: " + total);
    }
}
